version: '3.8'

services:
  kothari-computers-ui:
    container_name: kothari-computers-ui
    image: kothari-computers-ui

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "20021:80"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s